name = "calcpro"
compatibility_date = "2024-01-15"

[env.production]
name = "calcpro"
route = "calcpro.app.br/*"

[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "calcpro-assets"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://calcpro.app.br"